import { Navbar } from '@/components';

import { getSession } from './helpers';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getSession();

  return (
    <html lang='en'>
      <body>
        <Navbar user={session} />
        {children}
      </body>
    </html>
  );
}
